In [9]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

dataset = pd.read_csv('..\ML_input.csv')

We will split the dataset (obtained from sklearn load_digits) into a training and test set using the code below 

In [10]:
x_train, x_test, y_train, y_test = train_test_split(dataset, dataset, test_size=0.20,random_state=4) 
# test_size set the proportion of data to use as test data. The rest of the data will be used as training data

NN = MLPClassifier() # creates the neural network classifier

NN.fit(x_train, y_train) # trains the neural network

ValueError: Input X contains NaN.
MLPClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Now testing the model:

In [13]:
y_pred = NN.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)*100
confusion = confusion_matrix(y_test, y_pred)
print(accuracy)
print(confusion)

97.77777777777777
[[38  0  0  0  0  0  0  0  0  0]
 [ 0 32  0  0  0  0  0  0  0  0]
 [ 0  0 41  0  0  0  0  0  0  0]
 [ 0  0  0 32  0  1  0  0  0  0]
 [ 0  1  0  0 36  0  0  0  0  0]
 [ 0  0  0  0  0 37  0  0  0  1]
 [ 0  0  0  0  0  0 34  0  1  0]
 [ 0  0  0  0  0  0  0 37  0  1]
 [ 0  2  0  0  0  0  0  0 30  1]
 [ 0  0  0  0  0  0  0  0  0 35]]
