In [1]:
print('Hello World')

Hello World


In [1]:
import tensorflow as tf
import keras

Experimenting with Tensors:

In [70]:
x = tf.constant([[5,2],[1,3]])
#print(x)

x.numpy()

#print('dtype:',x.dtype)
#print('dtype:',x.shape)

#print(tf.ones(shape=(5,3)))
#print(tf.zeros(shape=(2,1)))

x = tf.random.normal(shape = (2,2), mean = 0.0, stddev=1.0)

#x = tf.random.uniform(shape=(2,2),minval=0,maxval=5,dtype='int32')

#print(x)


Variables: 
Special tensors used to store 'mutable states' such as weights of a neural network

In [75]:
initial_value = tf.random.normal(shape=(2,2))

a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.14624842,  0.65177846],
       [ 0.92965645, -0.02915145]], dtype=float32)>


In [79]:
new_value = tf.random.normal(shape=(2,2))
a.assign(new_value)

for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j]


added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j] + added_value[i,j]

Gradients


In [89]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))


tf.Tensor(
[[-0.07744095  0.03717181]
 [-0.83118665  0.6544504 ]], shape=(2, 2), dtype=float32)
None


In [119]:

with tf.GradientTape() as outer_tape:
    outer_tape.watch(a)
    with tf.GradientTape() as tape:
        tape.watch(a)
        c = tf.sqrt(tf.square(a)+tf.square(b))
        dc_da = tape.gradient(c,a)
        print(dc_da)
    dc2_da2 = outer_tape.gradient(dc_da,a)
    print(dc2_da2)


tf.Tensor(
[[-0.07744095  0.03717181]
 [-0.83118665  0.6544504 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.6262486 0.7254205]
 [2.2200336 0.9487737]], shape=(2, 2), dtype=float32)


Keras

In [123]:
class Linear(keras.layers.Layer):
    """y = w.x + b"""

    def __init__(self, units=32, input_dim=32):
        super().__init__()
        self.w = self.add_weight(
            shape=(input_dim, units), initializer="random_normal", trainable=True
        )
        self.b = self.add_weight(shape=(units,), initializer="zeros", trainable=True)

    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b


In [124]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import pandas as pd
import io
import os
import requests
import numpy as np
from sklearn import metrics

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", 
    na_values=['NA', '?'])

cars = df['name']

# Handle missing value
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

# Pandas to Numpy
x = df[['cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin']].values
y = df['mpg'].values # regression

# Build the neural network
model = Sequential()
model.add(Dense(25, input_dim=x.shape[1], activation='relu')) # Hidden 1
model.add(Dense(10, activation='relu')) # Hidden 2
model.add(Dense(1)) # Output
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

Epoch 1/100
13/13 - 2s - loss: 53572.1953 - 2s/epoch - 138ms/step
Epoch 2/100
13/13 - 0s - loss: 14407.2939 - 58ms/epoch - 4ms/step
Epoch 3/100
13/13 - 0s - loss: 4552.7632 - 59ms/epoch - 5ms/step
Epoch 4/100
13/13 - 0s - loss: 2675.4941 - 49ms/epoch - 4ms/step
Epoch 5/100
13/13 - 0s - loss: 1650.9501 - 56ms/epoch - 4ms/step
Epoch 6/100
13/13 - 0s - loss: 1078.4967 - 62ms/epoch - 5ms/step
Epoch 7/100
13/13 - 0s - loss: 746.5729 - 68ms/epoch - 5ms/step
Epoch 8/100
13/13 - 0s - loss: 543.9101 - 41ms/epoch - 3ms/step
Epoch 9/100
13/13 - 0s - loss: 415.6507 - 40ms/epoch - 3ms/step
Epoch 10/100
13/13 - 0s - loss: 335.8566 - 46ms/epoch - 4ms/step
Epoch 11/100
13/13 - 0s - loss: 284.4289 - 41ms/epoch - 3ms/step
Epoch 12/100
13/13 - 0s - loss: 249.1811 - 34ms/epoch - 3ms/step
Epoch 13/100
13/13 - 0s - loss: 226.9591 - 41ms/epoch - 3ms/step
Epoch 14/100
13/13 - 0s - loss: 212.9881 - 41ms/epoch - 3ms/step
Epoch 15/100
13/13 - 0s - loss: 205.1863 - 42ms/epoch - 3ms/step
Epoch 16/100
13/13 - 0s - 

In [46]:
def solution(P,Q):

    for i in range(0,len(P)):

        newlist.append(P[i])


    return 

print(Solution([a,b,c],[b,c,d]))

['1', '0', '0', '0', '0', '0']
0
